"$schema" = 'https://starship.rs/config-schema.json'

format = """
[   ](fg:#fffff)\
$directory\
$character\
"""

right_format = """
$git_branch\
$cmd_duration\
"""

[character]
error_symbol = "[/](bold #FF9580)"
success_symbol = "[/](bold #fff)"
 
[directory]
format = "[ $path](fg:#fff)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
format = '[ $symbol $branch ](purple)'

[cmd_duration]
min_time = 50
show_milliseconds = true
format = '[ $duration ](fg:#666666)'
